### ISSUE TITLE
Failing to build on MacOS 10.12

### ISSUE THREAD

**Issue by iluvcapra** [pomfort/mhl-tool#3]
I'm having trouble building this on the latest MacOS. I've added `-lssl` to my linker flags but it doesn't seem to be working, is this supported on the more recent MacOSs?

    /Users/iluvcapra/src/mhl-tool/src/mhltools_common/hashing.c:26:10: fatal error: 'openssl/md5.h' file not found
    #include <openssl/md5.h>

**Comment by wfoxall** [comment]
Probably too little too late here, but I've managed to compile fine on Big Sur targeting arm64 (Apple Silicon) and x86_64 (Intel) using XCode 13.1.
In the project Build Settings, I needed to change:

1. Search Paths > Header Search Paths:
Add path to wherever your OpenSSL include folder is. In my case:
Eg. `/opt/homebrew/opt/openssl@1.1/include/`
2. Linking > Other Linker Flags
Add the -L flag followed by path to OpenSSL lib folder.
Eg. `-L /opt/homebrew/opt/openssl@1.1/lib/`

Coming from Windows/Linux dev, I'm new to XCode, so perhaps there is a better way. But it worked.

One thing I came up against was that I was using an M1 Mac and wanted to compile for both M1 and Intel Macs. In this case, the OpenSSL library files in `/opt/homebrew/opt/openssl` were only arm64 binaries. So if you're in that boat, you might need to compile universal OpenSSL binaries and link to those.
Here's a good explanation: https://stackoverflow.com/a/69029436
